config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'lists#index'
  resources :lists, only: %i[index new show create] do
    resources :bookmarks, only: %i[new create]
  end

  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6, maximum: 20 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]
  def new
    @movies = Movie.all
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to @list
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @list = List.find(params[:id])
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <h2 class="text-white">New BookMark</h2>
</div>
<div class="container text-white">
  <%= simple_form_for([@list, @bookmark]) do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit class: 'btn btn-sm btn-success' %>
  <% end %>
  <%= link_to 'back', list_path(@list), class: "btn btn-sm btn-primary my-3" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <%= image_tag('pngaaa.com-88571.png')%>
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to 'Add List', new_list_path, class:'btn btn-sm btn-success' %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>
    <%= yield %>
    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fa-brands fa-github fa-xl" style="color: #FFFFFF;"></i></a>
      </div>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container"><h1 class="text-white text-center">My Lists</h1></div>
<div class="container">
  <div class="cards">
    <% @lists.each do |list| %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path 'background.jpg'%>)">
          <%= link_to list.name, list_path(list), class: 'text-decoration-none' %>
        </div>
    <% end %>
  </div>
</div>

<div class="container"></div>

app/views/lists/new.html.erb
<div class="container">
  <h2 class="text-white text-center">New List</h2>
</div>
<div class="container text-white">
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.submit class: 'btn btn-sm btn-success' %>
  <% end %>
  <%= link_to 'back', lists_path, class: "btn btn-sm btn-primary my-3" %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h2 class="text-white"><%= @list.name.capitalize %></h2>
  <div class="row">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="card m-2" style="width: 16rem;">
        <%= image_tag bookmark.movie.poster_url, class: "card-img-top"%>
          <div class="card-body">
              <h6 class="card-title"><strong><%= bookmark.movie.title %></strong>  ⭐<%= bookmark.movie.rating %></h6>
              <p class="card-text"><%= bookmark.comment %></p>
              <p class="card-text"><%= bookmark.movie.overview %></p>
              <%= link_to 'Delete BookMark', bookmark_path(bookmark),
            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:'btn btn-danger btn-sm text-white ' %>
          </div>
      </div>
    <% end %>
  </div>
  <%= link_to 'back', lists_path, class: "btn btn-sm btn-primary mt-3 text-white" %>
  <%= link_to 'Add BookMark', new_list_bookmark_path(@list), class: "btn btn-sm btn-warning mt-3 text-white" %>
</div>